server:
port: 8084
spring:
  application:
    name: congig-server
      cloud: 
      config:
      server:
      git:
      url: https://github.com/10419/microservicios_2023.git
      search-paths: config-data
      usernamne: 10419
      password: luismartin123
      default-label: main
    security:
    user:
    name: root
    password: s3cr3t